macro (add_sources _var)
    file(RELATIVE_PATH _relPath "${CMAKE_SOURCE_DIR}/src" "${CMAKE_CURRENT_SOURCE_DIR}")
    foreach(_src ${ARGN})
        if(_relPath)
            list (APPEND ${_var} "${_relPath}/${_src}")
        else()
            list (APPEND ${_var} "${_src}")
        endif()
    endforeach()
    if(_relPath)
        set(${_var} ${${_var}} PARENT_SCOPE)
    endif()
endmacro()

