macro (add_sources)
    file(RELATIVE_PATH _relPath "${CMAKE_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}")
    foreach(_src ${ARGN})
        if(_relPath)
            list (APPEND SRCS "${_relPath}/${_src}")
        else()
            list (APPEND SRCS "${_src}")
        endif()
    endforeach()
    if(_relPath)
        set(SRCS ${SRCS} PARENT_SCOPE)
    endif()
endmacro()

macro (add_sources_glob)
    foreach(_glob ${ARGN})
        file(GLOB_RECURSE _srcs RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}" ${_glob})
        add_sources(${_srcs})
    endforeach()
endmacro()
