dist: trusty
sudo: required

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

env:
  - DB=mysql
services:
  - mysql

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -y cmake doxygen naturaldocs
  - composer require --dev phpunit/phpunit "<6.0"
  - composer require --dev phpunit/phpcov "<4.0"
  - composer require --dev phpunit/dbunit "<3.0"
  - wget -q -O - https://github.com/sass/dart-sass/releases/download/1.29.0/dart-sass-1.29.0-linux-x64.tar.gz | tar xz && mv dart-sass/* /usr/bin/
  - sudo pip install mkdocs

before_script:
  - mkdir build
  - cd build
  - cmake .. -DDEBUG_MODE=ON -DWITH_MINIFY_JS=YES -DWITH_MINIFY_CSS=YES -DWITH_EXPENSIVE_TESTS=YES -DPHPUNIT_EXECUTABLE=../vendor/bin/phpunit
  - make && php www/db/configure_db_cli.php -p trustthetest -a install
  - make docs

script:
  - make lint
  - make check-frontend
  - make check-backend

after_script:
  - ../vendor/bin/phpcov merge --clover=coverage.xml --no-interaction TestCoverage/
  - bash <(curl -s https://codecov.io/bash) -c -f coverage.xml -F backend
  - bash <(curl -s https://codecov.io/bash) -c -f tests/frontend/coverage/lcov.info -F frontend

matrix:
  include:
    - php: 5.5
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: 5.6
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: 7.0
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: 7.1
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: nightly
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: hhvm
      env: DB=mariadb
      addons:
        mariadb: 10.1

  allow_failures:
    - php: nightly
    - php: hhvm

  fast_finish: true
