<?php
/** @file version.php
 * Version information for the application and database.
 *
 * This information is used, among other things, for the database update script.
 * DO NOT EDIT THIS FILE.
 */

return array(
  "version" => "1.2",
  "db_version" => "2"
);

?>
